envVarGroups:
  - name: sqlserver-creds
    envVars:
      - key: SA_PASSWORD
        value: ApiTestKey123!

services:
  - type: web
    name: api
    runtime: docker
    dockerfilePath: ./Dockerfile
    # runtime: image
    # image:
    #   url: jcdiegolopez/fluentis-core-develop:latest
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Server=sqlserver,1433;Database=pollocampero;User Id=sa;Password=ApiTestKey123!;TrustServerCertificate=True;
      - fromGroup: sqlserver-creds