name: CI-CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Ajusta según tu versión de .NET

      # 3. Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore FluentisCore.sln

      # 4. Construir y verificar linting (falla si hay advertencias o errores) -warnaserror
      - name: Build and check linting
        run: dotnet build FluentisCore.sln --configuration Release --no-restore

      # 5. Ejecutar pruebas (si tienes un proyecto de pruebas)
      - name: Run tests
        run: dotnet test FluentisCore.sln --no-build --verbosity normal

      # 6. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 7. Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Construir y subir la imagen a Docker Hub (solo en push a main)
      - name: Build and push Docker image on master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fluentis-core:latest
            ${{ secrets.DOCKER_USERNAME }}/fluentis-core:${{ github.sha }}

          # 8. Construir y subir la imagen a Docker Hub (solo en push a main)
      - name: Build and push Docker image on develop
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fluentis-core-develop:latest
            ${{ secrets.DOCKER_USERNAME }}/fluentis-core-develop:${{ github.sha }}